application: binarycrayon
version: 0-1-2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: favicon.gif
  upload: favicon.gif

- url: /nltk.*
  script: nltker.app

libraries:
- name: numpy
  version: "1.6.1"
- name: jinja2
  version: latest
