application: binarycrayon
version: 0-1-2
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: numpy
  version: "1.6.1"
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: "2.6"

handlers:

- url: /favicon.ico
  static_files: favicon.gif
  upload: favicon.gif

- url: /static
  static_dir: static

- url: /mapreduce(/.*)?
  script: mapreduce.main.APP
  login: admin

- url: /admin/?.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /.*
  script: main.APP

skip_files:
  - ^(.*/)?app\.yaml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^(.*/)?.*\.bak$
  - ^(.*/)?static/sass
  - ^(.*/)?.*/\.svn/.*$
